name: super_printer_example
description: "Demonstrates how to use the super_printer plugin."
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  super_printer:
    path: ../

  screenshot: ^2.1.0
  collection:

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/test_qr.png
    - assets/logo_text.png
    - assets/aljazary_logo_black.png
